---
- hosts: all
  tasks:
  - name: Initializing Kubernetes cluster
    shell: sudo kubeadm init
    register: output

  - name: Copying required files
    shell: |
     mkdir -p $HOME/.kube
     sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
     sudo chown $(id -u):$(id -g) $HOME/.kube/config
