---
- hosts: all
  tasks:
    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
      become: yes

    - name: Install device-mapper-persistent-data
      yum:
        name: device-mapper-persistent-data
        state: latest
      become: yes

    - name: Install lvm2
      yum:
        name: lvm2
        state: latest
      become: yes

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes

    - name: Enable Docker Edge repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: Enable Docker Test repo
      ini_file:
        dest: /etc/yum.repos.d/docer-ce.repo
        section: 'docker-ce-test'
        option: enabled
        value: 0
      become: yes

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Add user vagrant to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
      become: yes
    
    - name: Creating a repository file for Kubernetes
      file:
        path: /etc/yum.repos.d/kubernetes.repo
        state: touch
      become: yes

    - name: Adding repository details in Kubernetes repo file.
      blockinfile:
       path: /etc/yum.repos.d/kubernetes.repo
       block: |
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
          https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      become: yes

    - name: Install kubelet
      yum:
        name: kubelet
        state: latest
      become: yes

    - name: Install kubeadm
      yum:
        name: kubeadm
        state: latest
      become: yes

    - name: Install kubectl
      yum:
        name: kubectl
        state: latest
      become: yes

    - name: Start kubelet
      service:
        name: kubelet
        state: started
        enabled: yes
      become: yes
